config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/home", to: "static_pages#home", as: :home
  get "/about", to: "static_pages#about", as: :about
  get "/help", to: "static_pages#help", as: :help
  get "/contact", to: "static_pages#contact", as: :contact
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "password_resets/new"
  get "password_resets/edit"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :account_activations, only: :edit
  resources :password_resets, only: %i(new create edit update)
  resources :microposts, only: %i(create destroy)
  resources :relationships, only: %i(create destroy)
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t ".the" %><%= link_to t(".rubytutorial"), 
    Settings.footer.footer_rubyturorial %>
    <%= t ".by" %><%= link_to t(".f_name"), Settings.footer.footer_name %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t(".f_about"), about_path %></li>
      <li><%= link_to t(".contact_h"), contact_path %></li>
      <li><%= link_to t(".new"), Settings.news.news_host %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".h_sample_app"), root_path, class: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(".h_home"), root_path %></li>
        <li><%= link_to t(".h_help"), help_path %></li>
        <% if logged_in? %>
          <li><%= link_to current_user.name, users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t ".head_acount" %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t(".head_profile"), current_user %></li>
              <li><%= link_to t(".head_setting"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t(".head_logout"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".h_log_in"), Settings.header.header_login %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "application", "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= render "layouts/rails_default" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag :div, message, class: "alert alert-#{message_type}" %>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>